# Generated by Django 3.2.8 on 2021-10-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalGalleryApp', '0002_alter_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
